// SPDX-FileCopyrightText: 2026 Marcel Petrick
// SPDX-License-Identifier: GPL-3.0-or-later
package it.marcelpetrick.fork.monitoring

import it.marcelpetrick.fork.detection.Polygon
import it.marcelpetrick.fork.detection.Timing

enum class VisualMode { OFF, BORDER, ICON, FULL, PULSE }

enum class AudioMode { OFF, ONCE, REPEAT, CONTINUOUS }

/** The reminder sound; all three are generated by scripts/chime.py. */
enum class Chime { BELL, MARIMBA, GLASS }

/** Where inference runs. GPU is experimental and falls back to CPU when it cannot start. */
enum class Processor { CPU, GPU }

/**
 * Named detection timings, so families choose a feel instead of milliseconds. The raw values
 * stay adjustable; a combination that matches no preset is shown as custom.
 */
enum class Sensitivity(
    val trigger: Double,
    val triggerMs: Long,
    val clearMs: Long,
    val cooldownMs: Long,
) {
    /** Fewer reminders: strong, long evidence and a longer pause between reminders. */
    CONSERVATIVE(0.9, 1500, 500, 3000),

    /** The defaults. */
    NORMAL(0.75, 1000, 500, 1500),

    /** Quicker reminders for tables that want them. */
    RESPONSIVE(0.6, 750, 500, 1000),
    ;

    fun apply(timing: Timing): Timing = timing.copy(trigger = trigger, triggerMs = triggerMs, clearMs = clearMs, cooldownMs = cooldownMs)

    companion object {
        fun of(timing: Timing): Sensitivity? =
            entries.firstOrNull {
                it.trigger == timing.trigger && it.triggerMs == timing.triggerMs && it.clearMs == timing.clearMs &&
                    it.cooldownMs == timing.cooldownMs
            }
    }
}

enum class PoseModel(
    val asset: String,
) {
    FULL("pose_landmarker_full.task"),
    LITE("pose_landmarker_lite.task"),
}

data class Settings(
    val people: Int = 4,
    val camera: String = "",
    val model: PoseModel = PoseModel.FULL,
    val table: Polygon? = null,
    val seats: List<Polygon> = emptyList(),
    val timing: Timing = Timing(),
    val visual: VisualMode = VisualMode.BORDER,
    val audio: AudioMode = AudioMode.OFF,
    val volume: Int = 40,
    val repeatMs: Long = 3000,
    val graceMs: Long = 3000,
    val debug: Boolean = true,
    val statistics: Boolean = false,
    /** Upright analysis-image aspect (w/h) at calibration; 0 = not calibrated. */
    val calibrationAspect: Double = 0.0,
    /** Sensor rotation in degrees at calibration; -1 = unknown. */
    val calibrationRotation: Int = -1,
    val chime: Chime = Chime.BELL,
    val processor: Processor = Processor.CPU,
) {
    init {
        require(people in 1..4 && seats.size <= people)
        require(volume in 0..100 && repeatMs >= 1000 && graceMs >= 0)
        require(calibrationAspect.isFinite() && calibrationAspect >= 0)
        require(calibrationRotation in ROTATIONS)
    }

    /** Extension point for platform codecs (the app adds `decode`). */
    companion object {
        /** Sensor rotations in degrees; -1 means not calibrated yet. */
        val ROTATIONS = setOf(-1, 0, 90, 180, 270)
    }
}
