// Copyright (C) 2026 Marcel Petrick. SPDX-License-Identifier: GPL-3.0-or-later.
package it.marcelpetrick.fork.ui

import android.content.Context
import android.media.AudioAttributes
import android.media.SoundPool
import it.marcelpetrick.fork.R
import it.marcelpetrick.fork.monitoring.Sound

/** Executes [Sound] decisions; policy stays in [it.marcelpetrick.fork.monitoring.AlarmPolicy]. */
interface Speaker {
    /** Loads resources ahead of the first reminder. */
    fun prepare() = Unit

    fun play(
        sound: Sound,
        volume: Int,
    )

    fun release()
}

/**
 * Plays the bundled two-note chime (generated by scripts/chime.py). Notification-event
 * audio attributes let Do-Not-Disturb and the notification volume apply. "Continuous"
 * loops the chime until STOP. The pool is created on first use.
 */
class ChimeSpeaker(
    private val context: Context,
    private val factory: () -> SoundPool = {
        SoundPool
            .Builder()
            .setMaxStreams(1)
            .setAudioAttributes(
                AudioAttributes
                    .Builder()
                    .setUsage(AudioAttributes.USAGE_NOTIFICATION_EVENT)
                    .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                    .build(),
            ).build()
    },
) : Speaker {
    private var pool: SoundPool? = null
    private var chime = 0
    private var stream = 0
    private var loaded = false

    /** A play requested before the chime finished loading: (volume, loop). */
    private var pending: Pair<Int, Int>? = null

    override fun prepare() {
        if (pool != null) return
        pool =
            factory().also { created ->
                created.setOnLoadCompleteListener { _, _, status ->
                    loaded = status == 0
                    pending?.takeIf { loaded }?.let { (volume, loop) -> start(volume, loop) }
                    pending = null
                }
                chime = created.load(context, R.raw.chime, 1)
            }
    }

    override fun play(
        sound: Sound,
        volume: Int,
    ) {
        when (sound) {
            Sound.NONE -> Unit
            Sound.STOP -> stop()
            Sound.BEEP -> start(volume, loop = 0)
            Sound.START -> start(volume, loop = -1)
        }
    }

    private fun start(
        volume: Int,
        loop: Int,
    ) {
        prepare()
        stop()
        if (!loaded) {
            pending = volume to loop
            return
        }
        val level = volume.coerceIn(0, 100) / 100f
        stream = pool!!.play(chime, level, level, 1, loop, 1f)
    }

    private fun stop() {
        pending = null
        if (stream != 0) pool?.stop(stream)
        stream = 0
    }

    override fun release() {
        stop()
        pool?.release()
        pool = null
        loaded = false
    }
}
